@FamilyApi_HostAddress = http://localhost:5189

GET {{FamilyApi_HostAddress}}/weatherforecast/
Accept: application/json

GET {{FamilyApi_HostAddress}}/movies/
Accept: application/json

POST {{FamilyApi_HostAddress}}/dishes/
Accept: application/json
###
